# Configure the base image
ARG PYTHON_VERSION=3.10
FROM python:${PYTHON_VERSION}-slim

# Configure environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    MUJOCO_GL=egl

# Install system dependencies and uv (as root)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git curl libglib2.0-0 libegl1-mesa-dev ffmpeg \
    libusb-1.0-0-dev speech-dispatcher libgeos-dev portaudio19-dev \
    && curl -LsSf https://astral.sh/uv/install.sh | sh \
    && mv /root/.local/bin/uv /usr/local/bin/uv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Create application directory and set permissions
WORKDIR /lerobot-experiments

# Install Python dependencies for caching
COPY pyproject.toml README.md MANIFEST.in ./
COPY src/ src/

RUN python3.10 -m pip install --no-cache ".[all]"

# Copy working directory
COPY . /lerobot-experiments/

# Make sure git repo uses ssh origin
RUN git remote set-url origin git@github.com:Robot-Learning-Collective/lerobot-experiments.git

# Install pre-commit hooks for dev
RUN pre-commit install

# Set the default command
CMD ["/bin/bash"]
